### ISSUE TITLE
Playlist Support?

### ISSUE THREAD

**Issue by Phantop** [sean89503/Invidious_Cast#1]
As the title says, playlist support would be really useful for this!

**Comment by sean89503** [comment]
i like that idea ill try to get that implemented in the next update

**Comment by sean89503** [comment]
after looking into the invidious API I don't think there is a way to do playlist in a logical way that would work with a podcast manger. The issue is that videos only get a index number when added to the list so there is no way to find what date it was added to the list. So if i looked at the publish date of each video it would potentially be out of order and as older videos being add to a playlist might not show, depending on the podcast mangers behavior. .. typing this out kinda gave me some ideas lol

**Comment by Phantop** [comment]
For what it's worth, I put together quick playlist support on my own copy of the repo [here](https://github.com/Phantop/Invidious_Cast), although I did it on an older commit.

**Comment by sean89503** [comment]
well i must say i went down a complete different path, i noticed that videos were becoming more and more unavailable on invidious. So i decided to go to the source and use yt-dlp. I also want to make it so that if someone has a channel or playlist and they want 1000 feed items it would load fast as it could timeout on a podcast manager.  so i decided to make it save the xml's with the data. and here we are today lol. if you check the dev channel you can see were I am, so far its been working great, I've tested playlist and channels and both work. still need to writeup everything but you can try it if you want. Fun thing i learned is with YouTube channels is you can make them into a playlist by changing the UC at the start to UU

**Comment by sean89503** [comment]
main channel has updated code now
